### ISSUE TITLE
Sometimes I get errors when starting due to mixpanel not being reachable

### ISSUE THREAD

**Issue by DanielCaldwell** [amigocloud/qgis-amigocloud-plugin#6]
```
2018-01-16T18:43:11	1	Traceback (most recent call last):
			  File "C:/Programs/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/WHOEVER/.qgis2/python/plugins\qgis-amigocloud-plugin\__init__.py", line 35, in classFactory
			    return AmigoCloudQ(iface)
			  File "C:/Users/WHOEVER/.qgis2/python/plugins\qgis-amigocloud-plugin\amigocloud_q.py", line 62, in __init__
			    self.dlg = amigocloudDialog()
			  File "C:/Users/WHOEVER/.qgis2/python/plugins\qgis-amigocloud-plugin\amigocloud_dialog.py", line 67, in __init__
			    self.amigo_api.ac.get_user_email())
			  File "C:/Users/WHOEVER/.qgis2/python/plugins\qgis-amigocloud-plugin\amigo_api.py", line 63, in send_analytics_event
			    requests.get(url)
			  File "C:\Programs\OSGEO4~1\apps\Python27\lib\site-packages\requests\api.py", line 72, in get
			    return request('get', url, params=params, **kwargs)
			  File "C:\Programs\OSGEO4~1\apps\Python27\lib\site-packages\requests\api.py", line 58, in request
			    return session.request(method=method, url=url, **kwargs)
			  File "C:\Programs\OSGEO4~1\apps\Python27\lib\site-packages\requests\sessions.py", line 508, in request
			    resp = self.send(prep, **send_kwargs)
			  File "C:\Programs\OSGEO4~1\apps\Python27\lib\site-packages\requests\sessions.py", line 618, in send
			    r = adapter.send(request, **kwargs)
			  File "C:\Programs\OSGEO4~1\apps\Python27\lib\site-packages\requests\adapters.py", line 508, in send
			    raise ConnectionError(e, request=request)
			ConnectionError: HTTPConnectionPool(host='api.mixpanel.com', port=80): 
			Max retries exceeded with 
			url: /track/?data=eyJldmVudCI6ICJTdGFydCAoUUdJUy1wbHVnaW4pIiwgInByb3BlcnRpZXMiOiB7ImNhdGVnb3J5IjogIlVzZXIiLCAidG9rZW4iOiAiZjdhOGJhOGZiMWQ5ZTkxYWU0YzgzOTAzNWIyMGVjZDQiLCAiZGlzdGluY3RfaWQiOiAiZGFuaWVsQGFtaWdvY2xvdWQuY29tIiwgInVzZXJfaWQiOiAiMTEiLCAiYWN0aW9uIjogIlN0YXJ0IChRR0lTLXBsdWdpbikiLCAiJGVtYWlsIjogImRhbmllbEBhbWlnb2Nsb3VkLmNvbSIsICJzZXJ2ZXIiOiAiaHR0cHM6Ly93d3cuYW1pZ29jbG91ZC5jb20iLCAicGx1Z2luLXZlcnNpb24iOiAiMC40IiwgImVtYWlsIjogImRhbmllbEBhbWlnb2Nsb3VkLmNvbSIsICJsYWJlbCI6ICJkYW5pZWxAYW1pZ29jbG91ZC5jb20ifX0= 
			(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000BF9AD30>: 
			Failed to establish a new connection: 
			[Errno 10061] No connection could be made because the target machine actively refused it',))
```

**Comment by DanielCaldwell** [comment]
@vchernetsky can you assign this to Arturo? I don't see his username here yet.

**Comment by DanielCaldwell** [comment]
tried the new 0.6.1 build. Still didn't work: 

![2018-01-17 - amigocloud qgis plugin not working](https://user-images.githubusercontent.com/2634673/35062009-c028e976-fb77-11e7-8ac5-7a894723b478.gif)

**Comment by vchernetsky** [comment]
Fixed with this: https://github.com/amigocloud/qgis-amigocloud-plugin/commit/75f84273cde01a6b7ce224ba8d04db333ae7e95e
